---
title: "diseño experimental"
autor: "Ivan Ramos briceño"
format: html
editor: visual
---
```{r}
library(agricolae)
```

# DCA

Factor → dosis de fertilización nitrogenada (kg/ha) 0 ~ testigo 50 100 Diseño: DCA Repeticiones: 5 UE → 3 dosis x 5 rep = 15

```{r}
# Definición de los tratamientos (factor: dosis de fertilización nitrogenada)
tratamientos <- c("0", "50", "100")

# Diseño completamente al azar (DCA) con 5 repeticiones
diseño <- design.crd(
  trt = tratamientos,   # tratamientos
  r = 5,                # número de repeticiones
  seed = 123,           # semilla para reproducibilidad
  serie = 2             # numeración de las unidades experimentales
)

# Visualización del diseño generado
print(diseño)
```
# DBCA

Factor 1 → dosis de fertilización nitrogenada (Kg/ha) Factor 2 → cultivares papa peruanita canchan Diseño: DBCA Repeticiones: 4 UE → 3 dosis x 2 cultivos x 4 rep = 24

```{r}
trt<-c(3,2) # factorial 3x2
outdesign <-design.ab(trt, r=3, serie=2)
book<-outdesign$book
book
```

